;; This logfile was generated automatically by `xindy'
;; at 16.10.2017  16:02:14
;; Indexstyle: "/var/folders/tt/615w205s26146h55mgkt1dyw0000gn/T/eT05jgCGMH", Rawindex: "/var/folders/tt/615w205s26146h55mgkt1dyw0000gn/T/eapqTelhEo", Output: "Main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "àÈ»†" -> "U"
Letter-group: "†¼ËÐ" -> "C"
Letter-group: "¨Ð†" -> "I"
Letter-group: "†»€È" -> "C"
Letter-group: "¨Ë€€" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "†»€È" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¨Ë€€" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "àÈ»†" -> "U"