;; This logfile was generated automatically by `xindy'
;; at 14.03.2018  15:23:51
;; Indexstyle: "/var/folders/tt/615w205s26146h55mgkt1dyw0000gn/T/xP7XBNV4GE", Rawindex: "/var/folders/tt/615w205s26146h55mgkt1dyw0000gn/T/GvFg3jO838", Output: "Main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "Ë¨Ë" -> "R"
Letter-group: "„—»" -> "B"
Letter-group: "œ—»" -> "F"
Letter-group: "¨Ð†" -> "I"
Letter-group: "†»€È" -> "C"
Letter-group: "ËÚ60" -> "R"
Letter-group: "†€Ã" -> "C"
Letter-group: "€€„„" -> "A"
Letter-group: "Ã„„" -> "O"
Letter-group: "œ¨Ë" -> "F"
Letter-group: "œœÚ" -> "F"
Letter-group: "¨¤»" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€€„„" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "„—»" -> "B"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "†€Ã" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "œ—»" -> "F"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¨¤»" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ã„„" -> "O"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ë¨Ë" -> "R"