;; This logfile was generated automatically by `xindy'
;; at 30.01.2018  14:30:50
;; Indexstyle: "/var/folders/tt/615w205s26146h55mgkt1dyw0000gn/T/qAwNwZ_cCg", Rawindex: "/var/folders/tt/615w205s26146h55mgkt1dyw0000gn/T/Y9rWRtK405", Output: "Main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "„—»" -> "B"
Letter-group: "¨Ð†" -> "I"
Letter-group: "†»€È" -> "C"
Letter-group: "ËÚ60" -> "R"
Letter-group: "Ë¨Ë" -> "R"
Letter-group: "†€Ã" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "„—»" -> "B"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "†€Ã" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¨Ð†" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ë¨Ë" -> "R"